#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/fairbanks/fairbanks
else
 # accessed via sudo perms or fairbanks user
 PATH_PREFIX=~/fairbanks
fi

# establish directories we will be using based on user account
CONDA=$PATH_PREFIX/miniconda3/etc/profile.d/conda.sh
INPUT_FILE=$PATH_PREFIX/scripts/pdal/base-laz.json
SCAN_DIR=$PATH_PREFIX/external/lidar
cd $SCAN_DIR

# Activate the PDAL environment
source $CONDA
conda activate pdal

# <<<< BEGIN External drive file processing <<<<
# Clone/convert all .rxp files into .laz using PDAL and its input config json file
find $SCAN_DIR -name "*.rxp" | parallel pdal pipeline $INPUT_FILE --readers.rxp.filename={} --writers.las.filename={.}.laz
# Compress all original .rxp, .las, and .laz files
find $SCAN_DIR -name "*.rxp" | parallel gzip {}
find $SCAN_DIR -name "*.las" | parallel gzip {}
find $SCAN_DIR -name "*.laz" | parallel gzip {}
# >>>>> END External drive file processing >>>>>

# Repeat process for internal storage
conda deactivate
SCAN_DIR=$PATH_PREFIX/internal/lidar
cd $SCAN_DIR
conda activate pdal

# <<<< BEGIN Internal drive file processing <<<<
# Clone/convert all .rxp files into .laz using PDAL and its input config json file
find $SCAN_DIR -name "*.rxp" | parallel pdal pipeline $INPUT_FILE --readers.rxp.filename={} --writers.las.filename={.}.laz
# Compress all original .rxp, .las, and .laz files
find $SCAN_DIR -name "*.rxp" | parallel gzip {}
find $SCAN_DIR -name "*.las" | parallel gzip {}
find $SCAN_DIR -name "*.laz" | parallel gzip {}
# >>>>> END Internal drive file processing >>>>>
