#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/fairbanks/fairbanks
else
 # accessed via sudo perms or fairbanks user
 PATH_PREFIX=~/fairbanks
fi

# establish directories we will be using based on user account
if touch "$PATH_PREFIX""/external/test"; then
  rm $PATH_PREFIX/external/test
  if [ ! -d "$PATH_PREFIX""/external/lidar" ]; then
    mkdir "$PATH_PREFIX""/external/lidar"
  fi
  SCAN_DIR=$PATH_PREFIX/external/lidar
else
  if [ ! -d "$PATH_PREFIX""/internal" ]; then
    mkdir "$PATH_PREFIX""/internal"
  fi
  if [ ! -d "$PATH_PREFIX""/internal/lidar" ]; then
    mkdir "$PATH_PREFIX""/internal/lidar"
  fi
  SCAN_DIR=$PATH_PREFIX/internal/lidar
fi

# establish the directories we will be using based on user account
lidarcollect=$PATH_PREFIX/lidar-collect/build/LidarCollect

# Change to the directory where file scans are to be stored to
cd $SCAN_DIR

# GNSS Tower 1 Frame Scan
$lidarcollect --ip 192.168.0.128 --frame 3 30 130 0.04 0 90 0.04 GNSS1

# Wait for scanner to not be busy
sleep 10s

# GNSS Tower 4 Frame Scan
$lidarcollect --ip 192.168.0.128 --frame 3 30 130 0.04 90 180 0.04 GNSS2

#wait for scanner to not be busy
sleep 10s

# GNSS Tower 3 Frame Scan
$lidarcollect --ip 192.168.0.128 --frame 3 30 130 0.04 180 270 0.04 GNSS3

#wait for the scanner to not be busy
sleep 10s

# GNSS Tower 4 Frame Scan
$lidarcollect --ip 192.168.0.128 --frame 3 30 130 0.04 270 360 0.04 GNSS4

#wait for the scanner to not be busy
sleep 10s
