#!/bin/bash

if [ $USER = "fairbanks" ]; then
  # create path prefix based on user account
  PATH_PREFIX=~/fairbanks

  # create symlinks for the scripts used in the A-TLS process.
  ln -s $PATH_PREFIX/scripts/aws/syncaws $PATH_PREFIX/symlinks/syncaws
  ln -s $PATH_PREFIX/scripts/gpio/scanner_poweron $PATH_PREFIX/symlinks/scanner_poweron
  ln -s $PATH_PREFIX/scripts/gpio/scanner_poweroff $PATH_PREFIX/symlinks/scanner_poweroff
  ln -s $PATH_PREFIX/scripts/gpio/scanner_shutdown $PATH_PREFIX/symlinks/scanner_shutdown
  ln -s $PATH_PREFIX/scripts/gpio/scanner_status $PATH_PREFIX/symlinks/scanner_status
  ln -s $PATH_PREFIX/scripts/gpio/pivox_poweron $PATH_PREFIX/symlinks/pivox_poweron
  ln -s $PATH_PREFIX/scripts/gpio/pivox_poweroff $PATH_PREFIX/symlinks/pivox_poweroff
  ln -s $PATH_PREFIX/scripts/gpio/pivox_status $PATH_PREFIX/symlinks/pivox_status
  ln -s $PATH_PREFIX/scripts/logs/logs_split $PATH_PREFIX/symlinks/logs_split
  ln -s $PATH_PREFIX/scripts/scans/compress $PATH_PREFIX/symlinks/compress
  ln -s $PATH_PREFIX/scripts/scans/frame $PATH_PREFIX/symlinks/frame
  ln -s $PATH_PREFIX/scripts/scans/frame_gnss $PATH_PREFIX/symlinks/frame_gnss
  ln -s $PATH_PREFIX/scripts/vars/vars_init $PATH_PREFIX/symlinks/vars_init
  ln -s $PATH_PREFIX/lidar-collect/build/LidarCollect $PATH_PREFIX/symlinks/LidarCollect
  ln -s $PATH_PREFIX/scripts/pivox/pivox_capture $PATH_PREFIX/symlinks/pivox_capture
  ln -s $PATH_PREFIX/scripts/gpio/gpo_script $PATH_PREFIX/symlinks/gpo_script
else
  echo "[SYMLINKS]: Error, please run as fairbanks user."
fi
