#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/fairbanks/fairbanks
else
 # accessed via sudo perms or fairbanks user
 PATH_PREFIX=~/fairbanks
fi

# Define GPO python script and relay
GPO=$PATH_PREFIX/scripts/gpio/gpo_script
RELAY=4
CMD=OFF

# Extract pivox power status
$PATH_PREFIX/scripts/gpio/pivox_status
PWR_VAL=$?

if [ $PWR_VAL = "1" ]; then
  # Pivoxes are on, turn power off.
  $GPO -c $CMD -r $RELAY > /dev/null
  echo "[PVX_POWEROFF]: Pivoxes off."
elif [ $PWR_VAL = "0" ]; then
  # Pivoxes are already off.
  echo "[PVX_POWEROFF]: GPO already disconnected."
else
  # Invalid response from status check
  echo "[PVX_POWEROFF]: Error, invalid response from status check."
fi
