#!/bin/bash

# Set pathing to work from any user
if [ ~ = "/root" ]; then
  PATH_PREFIX=~/../home/fairbanks/fairbanks
else
 # accessed via sudo perms or fairbanks user
 PATH_PREFIX=~/fairbanks
fi

# set up relay info
GPO=$PATH_PREFIX/scripts/gpio/gpo_script
RELAY=4
CMD=ON

# Extract pivox power status
$PATH_PREFIX/scripts/gpio/pivox_status
PWR_VAL=$?

if [ $PWR_VAL = "1" ]; then
  # Power is already being provided.
  echo "[PVX_POWERON]: GPO already providing +Vcc."
elif [ $PWR_VAL = "0" ]; then
  # GPO is off, let's switch it on.
  $GPO -c $CMD -r $RELAY > /dev/null
  echo "[PVX_POWERON]: Pivox is warming up, press crtl+c to exit..."

  # wait for the pivoxes to boot up and respond to commands
  for i in {60..1}
  do
    echo -ne "\r$i""s remaining  "
    sleep 1
  done

  echo -ne "\r[PVX_POWERON]: Pivox On          \n"
else
  # Invalid response from status check.
  echo "[PVX_POWERON]: Error, invalid response from status check."
fi
